### PR TITLE
Addresses Isuue #33: Update keyword block_device to ebs_block_device

### PR DESCRIPTION
**Pull request by mminges**
Addresses Issue #33 where during the download of the bosh remote release, a "Network is unreachable" error is thrown when attempting to hit bosh.io. 

Terraform 0.4.0 deprecates the block_device attribute of aws_instance replacing it with three more specific attributes to specify block device mappings: root_block_device, ebs_block_device, and ephemeral_block_device.

This change specifies ebs_block_device for the bastion aws instance.

For more information see https://github.com/cloudfoundry-community/terraform-aws-cf-install/issues/33

### CODE REVIEW

**Comment by longnguyen11288** [comment]
:+1: will merge in when travis passes

**Comment by longnguyen11288** [comment]
Can you update travis to install new 0.4.0 in https://github.com/cloudfoundry-community/terraform-aws-cf-install/blob/master/.travis.yml#L3

**Comment by mminges** [comment]
Travis has passed now

**Comment by longnguyen11288** [comment]
thanks!

**Pull request merged**
